name: number_precision
description: Perform addition, subtraction, multiplication and division operations precisely using dart
version: 2.0.1+1
homepage: https://github.com/luoyelusheng/number_precision

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: number_precision.number_precision
        pluginClass: NumberPrecisionPlugin
      ios:
        pluginClass: NumberPrecisionPlugin
